version: '3.8'

services:
  app:
    build: .
    container_name: blog-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: asiye@1012

  mysql-db:
    image: mysql:8
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: asiye@1012
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
